import React from 'react'

const extToIcon: Record<string, string> = {
  c: '/icons/c-original.svg',
  h: '/icons/c-original.svg',
  cpp: '/icons/cplusplus-original.svg',
  hpp: '/icons/cplusplus-original.svg',
  cc: '/icons/cplusplus-original.svg',
  cxx: '/icons/cplusplus-original.svg',
  hxx: '/icons/cplusplus-original.svg',
  ts: '/icons/typescript-original.svg',
  tsx: '/icons/typescript-original.svg',
  js: '/icons/javascript-original.svg',
  jsx: '/icons/javascript-original.svg',
  mjs: '/icons/javascript-original.svg',
  cjs: '/icons/javascript-original.svg',
  py: '/icons/python-original.svg',
  pyw: '/icons/python-original.svg',
  html: '/icons/html5-original.svg',
  htm: '/icons/html5-original.svg',
  css: '/icons/css3-original.svg',
  scss: '/icons/css3-original.svg',
  sass: '/icons/css3-original.svg',
  less: '/icons/css3-original.svg',
  json: '/icons/json-original.svg',
  md: '/icons/markdown-original.svg',
  markdown: '/icons/markdown-original.svg',
  rs: '/icons/rust-plain.svg',
  go: '/icons/go-original-wordmark.svg',
  java: '/icons/java-original.svg',
  cs: '/icons/csharp-original.svg',
  php: '/icons/php-original.svg',
  rb: '/icons/ruby-original.svg',
  sh: '/icons/bash-original.svg',
  bash: '/icons/bash-original.svg',
  zsh: '/icons/bash-original.svg',
  fish: '/icons/bash-original.svg',
  yml: '/icons/yaml-original.svg',
  yaml: '/icons/yaml-original.svg',
  xml: '/icons/xml-original.svg',
  sql: '/icons/mysql-original.svg',
  vue: '/icons/vuejs-original.svg',
  svelte: '/icons/svelte-original.svg',
  svx: '/icons/svelte-original.svg',
  png: '/icons/file-image.svg',
  jpg: '/icons/file-image.svg',
  jpeg: '/icons/file-image.svg',
  gif: '/icons/file-image.svg',
  svg: '/icons/file-image.svg',
  webp: '/icons/file-image.svg',
  ico: '/icons/file-image.svg',
  bmp: '/icons/file-image.svg',
  pdf: '/icons/file-pdf.svg',
  zip: '/icons/file-zip.svg',
  tar: '/icons/file-zip.svg',
  gz: '/icons/file-zip.svg',
  rar: '/icons/file-zip.svg',
  '7z': '/icons/file-zip.svg',
  txt: '/icons/file-text.svg',
  log: '/icons/file-text.svg',
  env: '/icons/file-text.svg',
  gitignore: '/icons/git-original.svg',
  dockerfile: '/icons/docker-original.svg',
  makefile: '/icons/file-text.svg',
  cmake: '/icons/file-text.svg',
  toml: '/icons/file-text.svg',
  ini: '/icons/file-text.svg',
  cfg: '/icons/file-text.svg',
  conf: '/icons/file-text.svg',
  lock: '/icons/file-text.svg',
  map: '/icons/file-text.svg',
  wasm: '/icons/file-text.svg',
  swift: '/icons/swift-original.svg',
  kt: '/icons/kotlin-original.svg',
  kts: '/icons/kotlin-original.svg',
  lua: '/icons/lua-original.svg',
  r: '/icons/r-original.svg',
  scala: '/icons/scala-original.svg',
  dart: '/icons/dart-original.svg',
  ex: '/icons/elixir-original.svg',
  exs: '/icons/elixir-original.svg',
  haskell: '/icons/haskell-original.svg',
  hs: '/icons/haskell-original.svg',
  perl: '/icons/perl-original.svg',
  pl: '/icons/perl-original.svg',
  groovy: '/icons/groovy-original.svg',
  gradle: '/icons/groovy-original.svg',
  powershell: '/icons/powershell-original.svg',
  ps1: '/icons/powershell-original.svg',
  bat: '/icons/file-text.svg',
  cmd: '/icons/file-text.svg',
  asm: '/icons/file-text.svg',
  s: '/icons/file-text.svg',
  f90: '/icons/file-text.svg',
  f95: '/icons/file-text.svg',
  for: '/icons/file-text.svg',
  lisp: '/icons/file-text.svg',
  cl: '/icons/file-text.svg',
  erlang: '/icons/file-text.svg',
  erl: '/icons/file-text.svg',
  crystal: '/icons/file-text.svg',
  cr: '/icons/file-text.svg',
  nim: '/icons/file-text.svg',
  zig: '/icons/file-text.svg',
  v: '/icons/file-text.svg',
  vsh: '/icons/file-text.svg',
  d: '/icons/file-text.svg',
}

interface FileIconProps {
  fileName: string
  size?: number
}

export const FileIcon: React.FC<FileIconProps> = ({ fileName, size = 16 }) => {
  const ext = fileName.split('.').pop()?.toLowerCase() || ''
  const iconPath = extToIcon[ext] || '/icons/file-text.svg'
  
  return React.createElement('img', {
    src: iconPath,
    alt: ext,
    width: size,
    height: size,
    style: { display: 'inline-block', verticalAlign: 'middle' },
    loading: 'lazy',
    onError: (e: any) => {
      e.target.style.display = 'none'
    }
  })
}

export function getFileIcon(fileName: string): React.ReactNode {
  return React.createElement(FileIcon, { fileName })
}
