import React from 'react'

const ICON_BASE = './icons/'
const extToIcon: Record<string, string> = {
  c: ICON_BASE + 'c-original.svg',
  h: ICON_BASE + 'c-original.svg',
  cpp: ICON_BASE + 'cplusplus-original.svg',
  hpp: ICON_BASE + 'cplusplus-original.svg',
  cc: ICON_BASE + 'cplusplus-original.svg',
  cxx: ICON_BASE + 'cplusplus-original.svg',
  hxx: ICON_BASE + 'cplusplus-original.svg',
  ts: ICON_BASE + 'typescript-original.svg',
  tsx: ICON_BASE + 'typescript-original.svg',
  js: ICON_BASE + 'javascript-original.svg',
  jsx: ICON_BASE + 'javascript-original.svg',
  mjs: ICON_BASE + 'javascript-original.svg',
  cjs: ICON_BASE + 'javascript-original.svg',
  py: ICON_BASE + 'python-original.svg',
  pyw: ICON_BASE + 'python-original.svg',
  html: ICON_BASE + 'html5-original.svg',
  htm: ICON_BASE + 'html5-original.svg',
  css: ICON_BASE + 'css3-original.svg',
  scss: ICON_BASE + 'css3-original.svg',
  sass: ICON_BASE + 'css3-original.svg',
  less: ICON_BASE + 'css3-original.svg',
  json: ICON_BASE + 'json-original.svg',
  md: ICON_BASE + 'markdown-original.svg',
  markdown: ICON_BASE + 'markdown-original.svg',
  rs: ICON_BASE + 'rust-plain.svg',
  go: ICON_BASE + 'go-original-wordmark.svg',
  java: ICON_BASE + 'java-original.svg',
  cs: ICON_BASE + 'csharp-original.svg',
  php: ICON_BASE + 'php-original.svg',
  rb: ICON_BASE + 'ruby-original.svg',
  sh: ICON_BASE + 'bash-original.svg',
  bash: ICON_BASE + 'bash-original.svg',
  zsh: ICON_BASE + 'bash-original.svg',
  fish: ICON_BASE + 'bash-original.svg',
  yml: ICON_BASE + 'yaml-original.svg',
  yaml: ICON_BASE + 'yaml-original.svg',
  xml: ICON_BASE + 'xml-original.svg',
  sql: ICON_BASE + 'mysql-original.svg',
  vue: ICON_BASE + 'vuejs-original.svg',
  svelte: ICON_BASE + 'svelte-original.svg',
  svx: ICON_BASE + 'svelte-original.svg',
  png: ICON_BASE + 'file-image.svg',
  jpg: ICON_BASE + 'file-image.svg',
  jpeg: ICON_BASE + 'file-image.svg',
  gif: ICON_BASE + 'file-image.svg',
  svg: ICON_BASE + 'file-image.svg',
  webp: ICON_BASE + 'file-image.svg',
  ico: ICON_BASE + 'file-image.svg',
  bmp: ICON_BASE + 'file-image.svg',
  pdf: ICON_BASE + 'file-pdf.svg',
  zip: ICON_BASE + 'file-zip.svg',
  tar: ICON_BASE + 'file-zip.svg',
  gz: ICON_BASE + 'file-zip.svg',
  rar: ICON_BASE + 'file-zip.svg',
  '7z': ICON_BASE + 'file-zip.svg',
  txt: ICON_BASE + 'file-text.svg',
  log: ICON_BASE + 'file-text.svg',
  env: ICON_BASE + 'file-text.svg',
  gitignore: ICON_BASE + 'git-original.svg',
  dockerfile: ICON_BASE + 'docker-original.svg',
  makefile: ICON_BASE + 'file-text.svg',
  cmake: ICON_BASE + 'file-text.svg',
  toml: ICON_BASE + 'file-text.svg',
  ini: ICON_BASE + 'file-text.svg',
  cfg: ICON_BASE + 'file-text.svg',
  conf: ICON_BASE + 'file-text.svg',
  lock: ICON_BASE + 'file-text.svg',
  map: ICON_BASE + 'file-text.svg',
  wasm: ICON_BASE + 'file-text.svg',
  swift: ICON_BASE + 'swift-original.svg',
  kt: ICON_BASE + 'kotlin-original.svg',
  kts: ICON_BASE + 'kotlin-original.svg',
  lua: ICON_BASE + 'lua-original.svg',
  r: ICON_BASE + 'r-original.svg',
  scala: ICON_BASE + 'scala-original.svg',
  dart: ICON_BASE + 'dart-original.svg',
  ex: ICON_BASE + 'elixir-original.svg',
  exs: ICON_BASE + 'elixir-original.svg',
  haskell: ICON_BASE + 'haskell-original.svg',
  hs: ICON_BASE + 'haskell-original.svg',
  perl: ICON_BASE + 'perl-original.svg',
  pl: ICON_BASE + 'perl-original.svg',
  groovy: ICON_BASE + 'groovy-original.svg',
  gradle: ICON_BASE + 'groovy-original.svg',
  powershell: ICON_BASE + 'powershell-original.svg',
  ps1: ICON_BASE + 'powershell-original.svg',
  bat: ICON_BASE + 'file-text.svg',
  cmd: ICON_BASE + 'file-text.svg',
  asm: ICON_BASE + 'file-text.svg',
  s: ICON_BASE + 'file-text.svg',
  f90: ICON_BASE + 'file-text.svg',
  f95: ICON_BASE + 'file-text.svg',
  for: ICON_BASE + 'file-text.svg',
  lisp: ICON_BASE + 'file-text.svg',
  cl: ICON_BASE + 'file-text.svg',
  erlang: ICON_BASE + 'file-text.svg',
  erl: ICON_BASE + 'file-text.svg',
  crystal: ICON_BASE + 'file-text.svg',
  cr: ICON_BASE + 'file-text.svg',
  nim: ICON_BASE + 'file-text.svg',
  zig: ICON_BASE + 'file-text.svg',
  v: ICON_BASE + 'file-text.svg',
  vsh: ICON_BASE + 'file-text.svg',
  d: ICON_BASE + 'file-text.svg',
}

interface FileIconProps {
  fileName: string
  size?: number
}

export const FileIcon: React.FC<FileIconProps> = ({ fileName, size = 16 }) => {
  const ext = fileName.split('.').pop()?.toLowerCase() || ''
  const iconPath = extToIcon[ext] || ICON_BASE + 'file-text.svg'
  
  return React.createElement('img', {
    src: iconPath,
    alt: ext,
    width: size,
    height: size,
    style: { display: 'inline-block', verticalAlign: 'middle' },
    loading: 'lazy',
    onError: (e: any) => {
      e.target.style.display = 'none'
    }
  })
}

export function getFileIcon(fileName: string): React.ReactNode {
  return React.createElement(FileIcon, { fileName })
}
